package:
  name: "poly-validator"
  version: "0.1.0"

source:
  git_rev: v0.1.0
  git_url: https://github.com/billyz313/Geospatial-Data-Validation-Tool

build:
  noarch: python
  number: 0
  script: python -m pip install .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests

about:
  home: https://github.com/billyz313/Geospatial-Data-Validation-Tool
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "The Geospatial Data Validation Tool is designed to facilitate the validation and verification of geospatial datasets. This tool helps ensure the quality and consistency of geospatial data through various checks and validations. It supports common geospatial formats such as Shapefiles and GeoJSON."

extra:
  recipe-maintainers:
    - BillyZ313